import type { IDropdownOption } from "@fluentui/react";

export const countries: IDropdownOption[] = [
  { key: "Afghanistan", text: "Afghanistan" },
  { key: "Albania", text: "Albania" },
  { key: "Algeria", text: "Algeria" },
  { key: "Andorra", text: "Andorra" },
  { key: "Angola", text: "Angola" },
  { key: "Argentina", text: "Argentina" },
  { key: "Armenia", text: "Armenia" },
  { key: "Australia", text: "Australia" },
  { key: "Austria", text: "Austria" },
  { key: "Azerbaijan", text: "Azerbaijan" },
  { key: "Bahamas", text: "Bahamas" },
  { key: "Bahrain", text: "Bahrain" },
  { key: "Bangladesh", text: "Bangladesh" },
  { key: "Belarus", text: "Belarus" },
  { key: "Belgium", text: "Belgium" },
  { key: "Bhutan", text: "Bhutan" },
  { key: "Bolivia", text: "Bolivia" },
  { key: "Bosnia and Herzegovina", text: "Bosnia and Herzegovina" },
  { key: "Botswana", text: "Botswana" },
  { key: "Brazil", text: "Brazil" },
  { key: "Bulgaria", text: "Bulgaria" },
  { key: "Cambodia", text: "Cambodia" },
  { key: "Cameroon", text: "Cameroon" },
  { key: "Canada", text: "Canada" },
  { key: "Chile", text: "Chile" },
  { key: "China", text: "China" },
  { key: "Colombia", text: "Colombia" },
  { key: "Croatia", text: "Croatia" },
  { key: "Czech Republic", text: "Czech Republic" },
  { key: "Denmark", text: "Denmark" },
  { key: "Dominican Republic", text: "Dominican Republic" },
  { key: "Egypt", text: "Egypt" },
  { key: "Estonia", text: "Estonia" },
  { key: "Finland", text: "Finland" },
  { key: "France", text: "France" },
  { key: "Germany", text: "Germany" },
  { key: "Greece", text: "Greece" },
  { key: "Hungary", text: "Hungary" },
  { key: "Iceland", text: "Iceland" },
  { key: "India", text: "India" },
  { key: "Indonesia", text: "Indonesia" },
  { key: "Iran", text: "Iran" },
  { key: "Iraq", text: "Iraq" },
  { key: "Ireland", text: "Ireland" },
  { key: "Israel", text: "Israel" },
  { key: "Italy", text: "Italy" },
  { key: "Jamaica", text: "Jamaica" },
  { key: "Japan", text: "Japan" },
  { key: "Jordan", text: "Jordan" },
  { key: "Kazakhstan", text: "Kazakhstan" },
  { key: "Kenya", text: "Kenya" },
  { key: "Kuwait", text: "Kuwait" },
  { key: "Latvia", text: "Latvia" },
  { key: "Lebanon", text: "Lebanon" },
  { key: "Lithuania", text: "Lithuania" },
  { key: "Luxembourg", text: "Luxembourg" },
  { key: "Malaysia", text: "Malaysia" },
  { key: "Maldives", text: "Maldives" },
  { key: "Mexico", text: "Mexico" },
  { key: "Monaco", text: "Monaco" },
  { key: "Mongolia", text: "Mongolia" },
  { key: "Morocco", text: "Morocco" },
  { key: "Nepal", text: "Nepal" },
  { key: "Netherlands", text: "Netherlands" },
  { key: "New Zealand", text: "New Zealand" },
  { key: "Nigeria", text: "Nigeria" },
  { key: "Norway", text: "Norway" },
  { key: "Oman", text: "Oman" },
  { key: "Pakistan", text: "Pakistan" },
  { key: "Panama", text: "Panama" },
  { key: "Peru", text: "Peru" },
  { key: "Philippines", text: "Philippines" },
  { key: "Poland", text: "Poland" },
  { key: "Portugal", text: "Portugal" },
  { key: "Qatar", text: "Qatar" },
  { key: "Romania", text: "Romania" },
  { key: "Russia", text: "Russia" },
  { key: "Saudi Arabia", text: "Saudi Arabia" },
  { key: "Serbia", text: "Serbia" },
  { key: "Singapore", text: "Singapore" },
  { key: "Slovakia", text: "Slovakia" },
  { key: "Slovenia", text: "Slovenia" },
  { key: "South Africa", text: "South Africa" },
  { key: "South Korea", text: "South Korea" },
  { key: "Spain", text: "Spain" },
  { key: "Sri Lanka", text: "Sri Lanka" },
  { key: "Sweden", text: "Sweden" },
  { key: "Switzerland", text: "Switzerland" },
  { key: "Syria", text: "Syria" },
  { key: "Taiwan", text: "Taiwan" },
  { key: "Thailand", text: "Thailand" },
  { key: "Turkey", text: "Turkey" },
  { key: "Ukraine", text: "Ukraine" },
  { key: "United Arab Emirates", text: "United Arab Emirates" },
  { key: "United Kingdom", text: "United Kingdom" },
  { key: "United States", text: "United States" },
  { key: "Uruguay", text: "Uruguay" },
  { key: "Uzbekistan", text: "Uzbekistan" },
  { key: "Vatican City", text: "Vatican City" },
  { key: "Venezuela", text: "Venezuela" },
  { key: "Vietnam", text: "Vietnam" },
  { key: "Yemen", text: "Yemen" },
  { key: "Zambia", text: "Zambia" },
  { key: "Zimbabwe", text: "Zimbabwe" },
];